### ISSUE TITLE
Displayed number of indicators wrong

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#1027] opened 2018-08-27 13:22 UTC
in case all indicators in "Thema" and "Räumliche Gliederung" are enabled, the displayed number of indicators on every "Thema" or "Räumliche Gliederung" is the number of all indicators in portal view. This forces wrong assumptions by users. 

![grafik](https://user-images.githubusercontent.com/20972660/44662072-f580f980-aa0c-11e8-9f51-3a5ee476654e.png)

![grafik](https://user-images.githubusercontent.com/20972660/44662069-f1ed7280-aa0c-11e8-8919-3fdd4d4da647.png)

**Comment by jb3-2** [comment] 2018-09-03 08:51
This is a duplicate of #798

**Closed by jb3-2** 2018-09-03 08:51 UTC
Labels: bug
